### ISSUE TITLE
Log-in and show all list

### ISSUE THREAD

**Issue by slideray** [storvik/emacs-lastpass#11]
How to consistently execute the following commands — `login` and `lastpass-list-all`?
I'm doing:
```
(defun l-p-start ()
            (interactive)
            (lastpass-login)
            (lastpass-list-all))
```
but it dont work — only the first command is executed.

**Comment by storvik** [comment]
Due to the nature of `lastpass-login` this is not possible. The `lpass` command is running async and will not be logged in when the function call to `lastpass-list-all` is run. 

I have added a hook `lastpass-logged-in-hook` which can be used to achieve this. If you always want to run a certain function on successful login you can put `(add-hook 'lastpass-logged-in-hook 'lastpass-list-all)` in your config. 

Here's your function rewritten to use a local hook, which will not add the hook globally: 
```emacs-lisp
(defun l-p-start ()
  (interactive)
  (add-hook 'lastpass-logged-in-hook 'lastpass-list-all t t)
  (lastpass-login))
```

Be sure to update to the latest version to get the hook.

Hope that helps!

**Comment by slideray** [comment]
Grace!  It's work!
Thank you very much!
