### ISSUE TITLE
does emacs-lastpass work with two-factor authentication?

### ISSUE THREAD

**Issue by eamonnsullivan** [storvik/emacs-lastpass#2]
I can log in from the command line. When I try lastpass-login in emacs, I get asked for my password but not my authenticator code, and it doesn't appear to work.

If I log in from a terminal, emacs seems to see me as logged in, but lastpass-list-all doesn't work. 

LastPass status: Logged in as eamonn.sullivan@gmail.com.
M-x lastpass-list-all results in this error message:
lastpass-list-all-make-element: Wrong type argument: wholenump, -10

I am on a daily snapshot of emacs on Ubuntu 16.04: 
GNU Emacs 26.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)

**Comment by eamonnsullivan** [comment]
I get the same behaviour on Emacs 25.1 on Mac OS X.

**Comment by eamonnsullivan** [comment]
I'll open a second issue for the "Wrong type argument", because I think that's different. If I log in outside of emacs (providing the 2FA), then emacs-lastpass seems to be connecting, but something in my results is failing to parse.

**Comment by storvik** [comment]
Well I haven't used multifactor authentication so I can't say wether this is an acceptable way of implementing it, but.. 

`lastpass-login` now supports multifactor authentication. If you would like to use passcode instead of the lastpass authenticator app you should set `lastpass-multifactor-use-passcode` to `t`and it should prompt for passcode.
