### ISSUE TITLE
ls: unrecognized option…%an %ag %au’

### ISSUE THREAD

**Issue by guilhermecomum** [storvik/emacs-lastpass#8]
Hi, first of all, thanks for this amazing project :smile: 

Seems the lpass ls --format does't work any more.
So lastpass-list-all stop work =\

I don't know how to help, but I'm here for help fix this issue, if this is really a issue
:fist_oncoming:

**Comment by storvik** [comment]
Hello! 

Could you tell me OS and output of `lpass --version`? 

I have recently switched from Mac Os X to Ubuntu and is experiencing the same problem. It seems like the package from Ubuntu repos is outdated(v1.0). The [lpass changelog](https://github.com/lastpass/lastpass-cli/blob/master/CHANGELOG.md) states that the --format option was added in v1.1. Hence, the fix is to install lastpass-cli v1.2.1 from the [release page](https://github.com/lastpass/lastpass-cli/releases) following the instructions in the [readme](https://github.com/lastpass/lastpass-cli/blob/master/README.md).

Hope that helps :-)

**Comment by guilhermecomum** [comment]
Hi @storvik,
I'm using ubuntu and I update the lastpass-cli and now work perfectly!!

Thank you so much!

**Comment by storvik** [comment]
Glad I could help :smile:
