### ISSUE TITLE
emacs-lastpass and magit doesn't play well together

### ISSUE THREAD

**Issue by mattiasb** [storvik/emacs-lastpass#9]
Hi!

I was trying to use the `emacs-lastpass` integration with `auth-source` to be able to store the github OAuth token that is created when setting up a github account with [magit](https://magit.vc/).

I get a `Symbol's function definition is void: nil` which I've tracked down to [this line](https://github.com/magit/ghub/blob/master/ghub.el#L579) in [ghub.el](https://github.com/magit/ghub/).

I'm not sure if this is a bug in `emacs-lastpass` or in `ghub` so I'm putting the issue here and pinging in @tarsius .

**Comment by tarsius** [comment]
I believe having users calling that function and backends returning that function is what `auth-source` expects. It's a bit weird. See "Help for developers" in the manual.

**Comment by mattiasb** [comment]
I have no more experience with `auth-source` than from what I read 
yesterday trying to debug this, but this part from the 
`auth-source-search`-documentation suggests otherwise:

> The token **can** hold a :save-function key.  If you call that, the
> user will be prompted to save the data to the backend.  You can’t
> request that this should happen right after creation, because
> ‘auth-source-search’ has no way of knowing if the token is
> actually useful.  So the caller must arrange to call this function.

(Emphasis mine)

My take, from reading that, is that the `:save-function` key is optional. 
Maybe because the `auth-source` author wanted to support read-only
backends? I really have no clue here.

Regardless it seems to me that `emacs-lastpass` should learn how to
save stuff if this is indeed missing.

**Comment by storvik** [comment]
Thanks for providing some pointers. As soon as I get back to my Linux computer I'll check it out!

**Comment by tarsius** [comment]
I have interpreted "can" as "if the backend supports storing passwords persistently, then it *must* return a function so that the caller can call that if and only if it wants to do that. Otherwise it cannot, and therefore does not have to, return such a function."

With that interpretation `ghub`'s behavior is correct in that using a backend that does not allow storing the token persistently is of no use to it.

But there are at least two third-party backends that just save the secret instead of a saver function, so I'll probably handle that case in `ghub`.

**Comment by mattiasb** [comment]
I got all this working with the new forge package. My guess is that `ghub` changed somewhat or that I did something weird back then but it all works fine now.

**Comment by tarsius** [comment]
Yes, I changed something in `ghub` a while back, probably April. But I forgot to mention it here.
